apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: harbor
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZNVEl6TkRVPSJ9fX0=
type: kubernetes.io/dockerconfigjson
