version: '3'
services:
  etcd:
    image: docker.io/bitnami/etcd:3
    restart: always
    container_name: etcd
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local
