version: "3"
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "demo"
      MYSQL_USER: 'demo'
      MYSQL_PASS: 'demo'
    ports:
      - 3306:3306
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/log:/var/log/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
