version: "3"
services:
  redis:
    image: redis:5.0
    restart: always
    container_name: redis
    command: redis-server --appendonly yes --requirepass jimi@redis
    volumes:
      # 持久化数据文件挂载
      - ./redis/data:/data 
    ports:
      - 6379:6379
