---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: ops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hk-cmp-prod
  volumeMode: Filesystem
  csi:
    driver: com.tencent.cloud.csi.cfs
    volumeAttributes:
      fsid: ftcyuyer
      host: 10.255.254.10
      path: /prometheus
      vers: "4"
    volumeHandle: redis-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: hk-cmp-prod
  volumeMode: Filesystem
  volumeName: prometheus-pv

